import json
import time

import requests

cars = {
    "IPC-LEOP-2": [  # template_1.xlsx
        "pacifica-cn-002",
        "pacifica-cn-003",
        "pacifica-cn-006",
        "pacifica-cn-007",
        "pacifica-cn-008",
        "pacifica-cn-009",
        "pacifica-cn-010",
        "pacifica-cn-011",
        "pacifica-cn-012",
        "pacifica-cn-013",
        "pacifica-cn-014",
        "pacifica-cn-015",
        "pacifica-cn-026",
        "pacifica-cn-032",
        "pacifica-cn-033",
        "pacifica-cn-034",
        "pacifica-cn-035",
        "pacifica-cn-036",
        "pacifica-cn-037",
        "pacifica-cn-038",
        "pacifica-cn-039",
        "pacifica-cn-040",
        "pacifica-cn-041",
        "pacifica-cn-042",
        "pacifica-cn-043",
        "pacifica-cn-045",
        "pacifica-cn-046",
        "pacifica-cn-047",
        "pacifica-cn-048",
        "pacifica-cn-049",
        "pacifica-cn-050",
        "pacifica-cn-051",
        "pacifica-cn-052",
        "pacifica-cn-053",
        "pacifica-cn-054",
        "pacifica-cn-055",
    ],
    "IPC-0820-2": [  # template_2.xlsx
        "pacifica-cn-044",
        "pacifica-cn-056",
        "pacifica-cn-057",
        "pacifica-cn-058",
        "pacifica-cn-059",
        "pacifica-cn-060",
        "pacifica-cn-061",
        "pacifica-cn-062",
        "pacifica-cn-063",
        "pacifica-cn-064",
        "pacifica-cn-065",
        "pacifica-cn-066",
        "pacifica-cn-067",
        "pacifica-cn-068",
        "pacifica-cn-069",
        "pacifica-cn-070",
        "pacifica-cn-071",
        "pacifica-cn-072",
        "pacifica-cn-073",
        "pacifica-cn-074",
        "pacifica-cn-075",
        "pacifica-cn-076",
    ],
    "IPC-X8B-2": [  # template_3.xlsx
        "pacifica-cn-082",
        "pacifica-cn-083",
        "pacifica-cn-086",
        "pacifica-cn-090",
        "pacifica-cn-098",
        "pacifica-cn-231",
        "pacifica-cn-257",
        "pacifica-cn-276",
        "pacifica-cn-296",
        "pacifica-cn-308",
        "pacifica-cn-309",
        "pacifica-cn-310",
        "pacifica-cn-311",
        "pacifica-cn-312",
        "pacifica-cn-313",
        "pacifica-cn-314",
        "pacifica-cn-317",
        "pacifica-cn-328",
        "pacifica-cn-330",
        "pacifica-cn-363",
        "pacifica-cn-369",
        "pacifica-cn-373",
        "pacifica-cn-387",
        "pacifica-cn-389",
        "pacifica-cn-391",
        "pacifica-cn-392",
        "pacifica-cn-402",
        "pacifica-cn-440",
        "pacifica-cn-447",
        "pacifica-cn-451",
    ],
    "IPC-A-0": [  # template_4.xlsx
        "pacifica-cn-077",
        "pacifica-cn-078",
        "pacifica-cn-079",
        "pacifica-cn-080",
        "pacifica-cn-081",
        "pacifica-cn-084",
        "pacifica-cn-085",
        "pacifica-cn-087",
        "pacifica-cn-088",
        "pacifica-cn-089",
        "pacifica-cn-091",
        "pacifica-cn-092",
        "pacifica-cn-093",
        "pacifica-cn-094",
        "pacifica-cn-095",
        "pacifica-cn-096",
        "pacifica-cn-097",
        "pacifica-cn-099",
        "pacifica-cn-100",
        "pacifica-cn-203",
        "pacifica-cn-204",
        "pacifica-cn-205",
        "pacifica-cn-206",
        "pacifica-cn-207",
        "pacifica-cn-208",
        "pacifica-cn-209",
        "pacifica-cn-210",
        "pacifica-cn-211",
        "pacifica-cn-212",
        "pacifica-cn-213",
        "pacifica-cn-214",
        "pacifica-cn-215",
        "pacifica-cn-216",
        "pacifica-cn-217",
        "pacifica-cn-218",
        "pacifica-cn-219",
        "pacifica-cn-220",
        "pacifica-cn-221",
        "pacifica-cn-222",
        "pacifica-cn-223",
        "pacifica-cn-224",
        "pacifica-cn-225",
        "pacifica-cn-226",
        "pacifica-cn-227",
        "pacifica-cn-228",
        "pacifica-cn-229",
        "pacifica-cn-230",
        "pacifica-cn-232",
        "pacifica-cn-233",
        "pacifica-cn-234",
        "pacifica-cn-235",
        "pacifica-cn-236",
        "pacifica-cn-237",
        "pacifica-cn-238",
        "pacifica-cn-239",
        "pacifica-cn-240",
        "pacifica-cn-241",
        "pacifica-cn-242",
        "pacifica-cn-243",
        "pacifica-cn-244",
        "pacifica-cn-245",
        "pacifica-cn-246",
        "pacifica-cn-247",
        "pacifica-cn-248",
        "pacifica-cn-249",
        "pacifica-cn-250",
        "pacifica-cn-251",
        "pacifica-cn-252",
        "pacifica-cn-253",
        "pacifica-cn-254",
        "pacifica-cn-255",
        "pacifica-cn-256",
        "pacifica-cn-258",
        "pacifica-cn-259",
        "pacifica-cn-260",
        "pacifica-cn-261",
        "pacifica-cn-262",
        "pacifica-cn-263",
        "pacifica-cn-264",
        "pacifica-cn-265",
        "pacifica-cn-266",
        "pacifica-cn-267",
        "pacifica-cn-268",
        "pacifica-cn-269",
        "pacifica-cn-270",
        "pacifica-cn-271",
        "pacifica-cn-272",
        "pacifica-cn-273",
        "pacifica-cn-274",
        "pacifica-cn-275",
        "pacifica-cn-277",
        "pacifica-cn-278",
        "pacifica-cn-279",
        "pacifica-cn-280",
        "pacifica-cn-281",
        "pacifica-cn-282",
        "pacifica-cn-283",
        "pacifica-cn-284",
        "pacifica-cn-285",
        "pacifica-cn-286",
        "pacifica-cn-287",
        "pacifica-cn-288",
        "pacifica-cn-289",
        "pacifica-cn-290",
        "pacifica-cn-291",
        "pacifica-cn-292",
        "pacifica-cn-293",
        "pacifica-cn-294",
        "pacifica-cn-295",
        "pacifica-cn-297",
        "pacifica-cn-298",
        "pacifica-cn-299",
        "pacifica-cn-300",
        "pacifica-cn-301",
        "pacifica-cn-302",
        "pacifica-cn-303",
        "pacifica-cn-305",
        "pacifica-cn-306",
        "pacifica-cn-307",
        "pacifica-cn-315",
        "pacifica-cn-316",
        "pacifica-cn-318",
        "pacifica-cn-319",
        "pacifica-cn-321",
        "pacifica-cn-322",
        "pacifica-cn-324",
        "pacifica-cn-325",
        "pacifica-cn-326",
        "pacifica-cn-327",
        "pacifica-cn-329",
        "pacifica-cn-331",
        "pacifica-cn-332",
        "pacifica-cn-333",
        "pacifica-cn-335",
        "pacifica-cn-336",
        "pacifica-cn-338",
        "pacifica-cn-339",
        "pacifica-cn-340",
        "pacifica-cn-341",
        "pacifica-cn-342",
        "pacifica-cn-344",
        "pacifica-cn-345",
        "pacifica-cn-346",
        "pacifica-cn-347",
        "pacifica-cn-348",
        "pacifica-cn-349",
        "pacifica-cn-350",
        "pacifica-cn-351",
        "pacifica-cn-352",
        "pacifica-cn-353",
        "pacifica-cn-354",
        "pacifica-cn-355",
        "pacifica-cn-356",
        "pacifica-cn-357",
        "pacifica-cn-358",
        "pacifica-cn-359",
        "pacifica-cn-360",
        "pacifica-cn-361",
        "pacifica-cn-362",
        "pacifica-cn-364",
        "pacifica-cn-365",
        "pacifica-cn-366",
        "pacifica-cn-367",
        "pacifica-cn-368",
        "pacifica-cn-370",
        "pacifica-cn-371",
        "pacifica-cn-372",
        "pacifica-cn-374",
        "pacifica-cn-375",
        "pacifica-cn-376",
        "pacifica-cn-377",
        "pacifica-cn-378",
        "pacifica-cn-379",
        "pacifica-cn-380",
        "pacifica-cn-381",
        "pacifica-cn-382",
        "pacifica-cn-383",
        "pacifica-cn-384",
        "pacifica-cn-385",
        "pacifica-cn-386",
        "pacifica-cn-388",
        "pacifica-cn-390",
        "pacifica-cn-393",
        "pacifica-cn-394",
        "pacifica-cn-395",
        "pacifica-cn-396",
        "pacifica-cn-397",
        "pacifica-cn-398",
        "pacifica-cn-399",
        "pacifica-cn-400",
        "pacifica-cn-401",
        "pacifica-cn-403",
        "pacifica-cn-405",
        "pacifica-cn-406",
        "pacifica-cn-407",
        "pacifica-cn-408",
        "pacifica-cn-409",
        "pacifica-cn-410",
        "pacifica-cn-411",
        "pacifica-cn-412",
        "pacifica-cn-413",
        "pacifica-cn-414",
        "pacifica-cn-415",
        "pacifica-cn-416",
        "pacifica-cn-417",
        "pacifica-cn-418",
        "pacifica-cn-419",
        "pacifica-cn-420",
        "pacifica-cn-421",
        "pacifica-cn-422",
        "pacifica-cn-423",
        "pacifica-cn-424",
        "pacifica-cn-425",
        "pacifica-cn-426",
        "pacifica-cn-427",
        "pacifica-cn-428",
        "pacifica-cn-429",
        "pacifica-cn-430",
        "pacifica-cn-431",
        "pacifica-cn-432",
        "pacifica-cn-433",
        "pacifica-cn-434",
        "pacifica-cn-435",
        "pacifica-cn-436",
        "Pacifica-cn-437",
        "pacifica-cn-438",
        "pacifica-cn-439",
        "pacifica-cn-441",
        "pacifica-cn-442",
        "pacifica-cn-443",
        "pacifica-cn-444",
        "pacifica-cn-445",
        "pacifica-cn-446",
        "pacifica-cn-448",
        "pacifica-cn-449",
        "pacifica-cn-450",
        "pacifica-cn-304",
        "pacifica-cn-320",
        "pacifica-cn-323",
        "pacifica-cn-334",
        "pacifica-cn-337",
        "pacifica-cn-343",
        "pacifica-cn-404",
    ],
    "IPC-C-0": [  # template_5.xlsx
        "pacifica-cn-001",
        "pacifica-cn-004",
        "pacifica-cn-005",
        "pacifica-cn-021",
        "pacifica-cn-022",
        "pacifica-cn-023",
        "pacifica-cn-024",
        "pacifica-cn-025",
        "pacifica-cn-027",
        "pacifica-cn-028",
        "pacifica-cn-029",
        "pacifica-cn-030",
        "pacifica-cn-031",
    ],
    "XCU-0820-14": [  # template_7.xlsx
        "pacifica-cn-101",
        "pacifica-cn-104",
        "pacifica-cn-105",
        "pacifica-cn-106",
        "pacifica-cn-107",
        "pacifica-cn-108",
    ],
    "XCU-X8B-14": [  # template_8.xlsx
        "pacifica-cn-109",
        "pacifica-cn-110",
        "pacifica-cn-111",
        "pacifica-cn-112",
        "pacifica-cn-113",
        "pacifica-cn-114",
        "pacifica-cn-115",
        "pacifica-cn-116",
        "pacifica-cn-117",
        "pacifica-cn-118",
        "pacifica-cn-119",
        "pacifica-cn-120",
        "pacifica-cn-121",
        "pacifica-cn-122",
        "pacifica-cn-123",
        "pacifica-cn-124",
        "pacifica-cn-125",
        "pacifica-cn-126",
        "pacifica-cn-127",
        "pacifica-cn-128",
        "pacifica-cn-129",
        "pacifica-cn-130",
        "pacifica-cn-131",
        "pacifica-cn-132",
        "pacifica-cn-133",
        "pacifica-cn-134",
        "pacifica-cn-135",
        "pacifica-cn-136",
        "pacifica-cn-137",
        "pacifica-cn-138",
        "pacifica-cn-139",
        "pacifica-cn-140",
        "pacifica-cn-141",
        "pacifica-cn-142",
        "pacifica-cn-143",
        "pacifica-cn-144",
        "pacifica-cn-145",
        "pacifica-cn-146",
        "pacifica-cn-147",
        "pacifica-cn-148",
        "pacifica-cn-149",
        "pacifica-cn-150",
        "pacifica-cn-151",
        "pacifica-cn-152",
        "pacifica-cn-153",
        "pacifica-cn-154",
        "pacifica-cn-155",
        "pacifica-cn-156",
        "pacifica-cn-157",
        "pacifica-cn-158",
        "pacifica-cn-159",
        "pacifica-cn-160",
        "pacifica-cn-161",
        "pacifica-cn-162",
        "pacifica-cn-163",
        "pacifica-cn-164",
        "pacifica-cn-165",
        "pacifica-cn-166",
    ],
    "XCU-0820-A": [
        "pacifica-cn-102",
        "pacifica-cn-103",
    ],
}

template_xlsx = {
    "IPC-LEOP-2": "/home/quanxipeng/file/IPC-LEOP-2.xlsx",
    "IPC-0820-2": "/home/quanxipeng/file/IPC-0820-2.xlsx",
    "IPC-X8B-2": "/home/quanxipeng/file/IPC-X8B-2.xlsx",
    "IPC-A-0": "/home/quanxipeng/file/IPC-A-0.xlsx",
    "IPC-C-0": "/home/quanxipeng/file/IPC-C-0.xlsx",
    "XCU-0820-14": "/home/quanxipeng/file/XCU-0820-14.xlsx",
    "XCU-X8B-14": "/home/quanxipeng/file/XCU-X8B-14.xlsx",
    "XCU-0820-A": "/home/quanxipeng/file/XCU-0820-A.xlsx",
}


def handle_one_car(car: str, file: str, module: str):
    cookies = {
        "jwt_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ3ZWl4aW5fdXNlcmlkIjoiUGVuZ1F1YW5YaSIsImV4cGlyZV90aW1lc3RhbXAiOjE2NTI1MDk0OTguNTI5NzQzLCJ2ZXJzaW9uIjoiMC4xIn0.creZcEyzOZoZ2onodYBrH-nBKI3-ySh5tGIMryxLmds",
    }
    base_url = "http://vms.autox.tech"

    response = requests.get(url=f"{base_url}/api/vehicles/{car}", cookies=cookies)
    if response.status_code != 200:
        raise Exception(f"{car} 获取车ID失败, 原因: {response.text}")

    car_text = json.loads(response.text)
    car_id = car_text["id"]

    # 修改module
    car_text["model"] = module
    res = requests.put(
        url=f"{base_url}/api/vehicles/{car_id}", cookies=cookies, json=car_text
    )
    if res.status_code != 200:
        raise Exception(f"{car} 修改车Module失败, 原因: {response.text}")

    # 上传文件
    with open(file, mode="rb") as f:
        files = {"file": f}
        r = requests.post(
            url=f"{base_url}/api/vehicles/{car_id}/hardware_file",
            cookies=cookies,
            files=files,
        )
        print(f"{car}: {r.text}")


if __name__ == "__main__":
    # wrong_cars = []
    #
    # for car_group, car_list in cars.items():
    #     file = template_xlsx.get(car_group)
    #
    #     for car in car_list:
    #         try:
    #             handle_one_car(car, file, module=car_group)
    #         except Exception as e:
    #             print(e)
    #             wrong_cars.append(car)
    #         time.sleep(0.2)
    # #
    # # print("------------- wrong_cars")
    # # for car in wrong_cars:
    # #     print(car)

    handle_one_car(
        "pacifica-cn-437", "/home/quanxipeng/file/IPC-A-0.xlsx", "IPC-A-0"
    )
